# Generated by Django 4.1.2 on 2022-10-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalityRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TechRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lineup.person')),
                ('instrument', models.CharField(max_length=50)),
            ],
            bases=('lineup.person',),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lineup.person')),
                ('role', models.CharField(max_length=50)),
            ],
            bases=('lineup.person',),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linecheck_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup.act')),
                ('hospitality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup.hospitalityrider')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup.techrider')),
            ],
        ),
        migrations.AddField(
            model_name='techrider',
            name='tour_eng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup.crew'),
        ),
        migrations.AddField(
            model_name='act',
            name='artists',
            field=models.ManyToManyField(to='lineup.artist'),
        ),
    ]
