# Generated by Django 4.1.2 on 2022-10-05 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='hospitality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lineup.hospitalityrider'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lineup.techrider'),
        ),
    ]
