# Generated by Django 4.1.2 on 2022-10-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0003_alter_performance_hospitality_alter_performance_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='tour_eng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineup.crew'),
        ),
    ]
