# Generated by Django 4.1.2 on 2022-10-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0004_act_tour_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='techrider',
            name='mixer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
