# Generated by Django 4.1.2 on 2022-10-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0005_techrider_mixer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='hospitality',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='tech',
        ),
        migrations.AddField(
            model_name='performance',
            name='hospitality_brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='tech_brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techrider',
            name='spec_sheet',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
